version: '3.8'
services: 
    api-service:
        build: ./
        restart: always
        container_name: docker-monitor
        volumes: 
            - ./Docker-engine-api/:/usr/src/app/
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1
