version: '3.8'
services: 
    api-service:
        build: ./
        restart: always
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1
            
         